export const queryKeys = {
  session: ["session"],
  patientDashboard: ["patient-dashboard"],
  patientProfessionals: ["patient-professionals"],
  patientProfessionalDetail: (id: string) => ["patient-professional-detail", id],
  patientAppointments: ["patient-appointments"],
  patientHealth: ["patient-health"],
  patientStudies: ["patient-studies"],
  patientPrescriptions: ["patient-prescriptions"],
  patientProfile: ["patient-profile"],
  patientSettings: ["patient-settings"],
  professionalDashboard: ["professional-dashboard"],
  professionalPatients: ["professional-patients"],
  professionalPatientDetail: (id: string) => ["professional-patient-detail", id],
  professionalSchedule: ["professional-schedule"],
  professionalPrescriptions: ["professional-prescriptions"],
  professionalOffices: ["professional-offices"],
  professionalOfficeDetail: (id: string) => ["professional-office-detail", id],
  professionalProfile: ["professional-profile"],
  professionalSettings: ["professional-settings"],
} as const;
